name: Bump and Publish Development Branch

on:
  push:
    branches: [ development ]
  workflow_dispatch:
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4.1.3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Bump Version
        id: bump
        uses: Plugily-Projects/version-bump-action@v8
        with:
          github-token: ${{ secrets.github_token }}
          auto-version-bump: true
      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"
  publish:
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4.1.3
        with:
          ref: 'development'
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jdk
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew publishMavenPublicationToSnapshotsRepository
        env:
          MAVEN_USERNAME: ${{ secrets.SNAPSHOTSUSERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SNAPSHOTSPASSWORD }}